### ISSUE TITLE
https://a-lohas.jp/

### ISSUE THREAD

**Issue by olstice** [thisisu/hosts_adultxxx#2]
this website is not added in your list

**Comment by thisisu** [comment]
Can you test it out with the latest hosts and let me know if there is still an issue?
There was a lot to block! Thanks for your help

**Comment by olstice** [comment]
> ?

it didnt block the redirect im afraid 

unless did i download the wrong file version this is what i downloaded

[hosts_adultxxx-master(1).zip](https://github.com/user-attachments/files/17681454/hosts_adultxxx-master.1.zip)

**Comment by thisisu** [comment]
Yes that's correct.
Sorry you're still experiencing an issue.

Can you verify if these two domains are in your hosts file located at: C:\Windows\System32\drivers\etc\hosts

```
go.cbro.win
enviousratio.com
```
Thank you

**Comment by thisisu** [comment]
Ok great
Did you flush dns as well? If not can you try that?

In a command prompt window: ipconfig /flushdns

**Comment by olstice** [comment]
> Ok great Did you flush dns as well? If not can you try that?
> 
> In a command prompt window: ipconfig /flushdns

it worked! i forgot to do ipconfig /flushdns again

also may i ask you a question relating to your host file?

**Comment by thisisu** [comment]
Great!
Yes of course

**Comment by olstice** [comment]
> Great! Yes of course

how did you manage to block the href link request that were causing the redirect

i cant even stay long enough in its network activity of dev tools because it automatically redirects to the spam url

giving me all the request of that url instead of the original one with the redirect request

**Comment by olstice** [comment]
> Great! Yes of course

please go into extream detail i really want to know so hopfully if this occures again i wont have to bother you or someone else as much

plus i like being self reliant if possible

**Comment by thisisu** [comment]
> > Great! Yes of course
> 
> how did you manage to block the href link request that were causing the redirect
> 
> i cant even stay long enough in its network activity of dev tools because it automatically redirects to the spam url
> 
> giving me all the request of that url instead of the original one with the redirect request

I opened [Fiddler Classic](https://www.telerik.com/fiddler/fiddler-classic) before visiting the site. And once I started clicking around there, all the traffic was getting captured within Fiddler.
Most of these no longer appear but I suspect the biggest culprit still shows.
![image](https://github.com/user-attachments/assets/e78b26f3-1bff-4082-992c-5382d9e4c03c)

**Comment by olstice** [comment]
> > > Great! Yes of course
> > 
> > 
> > how did you manage to block the href link request that were causing the redirect
> > i cant even stay long enough in its network activity of dev tools because it automatically redirects to the spam url
> > giving me all the request of that url instead of the original one with the redirect request
> 
> I opened [Fiddler Classic](https://www.telerik.com/fiddler/fiddler-classic) before visiting the site. And once I started clicking around there, all the traffic was getting captured within Fiddler. Most of these no longer appear but I suspect the biggest culprit still shows. ![image](https://private-user-images.githubusercontent.com/35790653/384579003-e78b26f3-1bff-4082-992c-5382d9e4c03c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODM4NTgsIm5iZiI6MTczMTE4MzU1OCwicGF0aCI6Ii8zNTc5MDY1My8zODQ1NzkwMDMtZTc4YjI2ZjMtMWJmZi00MDgyLTk5MmMtNTM4MmQ5ZTRjMDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDIwMTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNmRkMGY4MzUxNmEwYTVjMDg1NGMzOGE0ODNlOTQ1YzY4YzAxZjIwOTcxYTExYzc4YzRjNzk5ODU2NjRiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1cpNvLOCCciqcaAGQo8wu6ScOctqcbDYAGpCejPp4Qk)

is this a paid or free software?

**Comment by thisisu** [comment]
> > Great! Yes of course
> 
> 
> 
> how did you manage to block the href link request that were causing the redirect
> 
> 
> 
> i cant even stay long enough in its network activity of dev tools because it automatically redirects to the spam url
> 
> 
> 
> giving me all the request of that url instead of the original one with the redirect request

I ran Fiddler Classic to capture the requests being made. It was a bit tricky

Free

**Comment by thisisu** [comment]
> > > > Great! Yes of course
> 
> > > 
> 
> > > 
> 
> > > how did you manage to block the href link request that were causing the redirect
> 
> > > i cant even stay long enough in its network activity of dev tools because it automatically redirects to the spam url
> 
> > > giving me all the request of that url instead of the original one with the redirect request
> 
> > 
> 
> > I opened [Fiddler Classic](https://www.telerik.com/fiddler/fiddler-classic) before visiting the site. And once I started clicking around there, all the traffic was getting captured within Fiddler. Most of these no longer appear but I suspect the biggest culprit still shows. ![image](https://private-user-images.githubusercontent.com/35790653/384579003-e78b26f3-1bff-4082-992c-5382d9e4c03c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODM4NTgsIm5iZiI6MTczMTE4MzU1OCwicGF0aCI6Ii8zNTc5MDY1My8zODQ1NzkwMDMtZTc4YjI2ZjMtMWJmZi00MDgyLTk5MmMtNTM4MmQ5ZTRjMDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDIwMTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNmRkMGY4MzUxNmEwYTVjMDg1NGMzOGE0ODNlOTQ1YzY4YzAxZjIwOTcxYTExYzc4YzRjNzk5ODU2NjRiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1cpNvLOCCciqcaAGQo8wu6ScOctqcbDYAGpCejPp4Qk)
> 
> 
> 
> is this a paid or free software?

Free

**Comment by olstice** [comment]
> > > > > Great! Yes of course
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > how did you manage to block the href link request that were causing the redirect
> > 
> > 
> > > > i cant even stay long enough in its network activity of dev tools because it automatically redirects to the spam url
> > 
> > 
> > > > giving me all the request of that url instead of the original one with the redirect request
> > 
> > 
> > > 
> > 
> > 
> > > I opened [Fiddler Classic](https://www.telerik.com/fiddler/fiddler-classic) before visiting the site. And once I started clicking around there, all the traffic was getting captured within Fiddler. Most of these no longer appear but I suspect the biggest culprit still shows. ![image](https://private-user-images.githubusercontent.com/35790653/384579003-e78b26f3-1bff-4082-992c-5382d9e4c03c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExODM4NTgsIm5iZiI6MTczMTE4MzU1OCwicGF0aCI6Ii8zNTc5MDY1My8zODQ1NzkwMDMtZTc4YjI2ZjMtMWJmZi00MDgyLTk5MmMtNTM4MmQ5ZTRjMDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDIwMTkxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNmRkMGY4MzUxNmEwYTVjMDg1NGMzOGE0ODNlOTQ1YzY4YzAxZjIwOTcxYTExYzc4YzRjNzk5ODU2NjRiYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1cpNvLOCCciqcaAGQo8wu6ScOctqcbDYAGpCejPp4Qk)
> > 
> > 
> > is this a paid or free software?
> 
> Free

so you open the software application

you then go to the website that has the redirect request and the software saves all the request that came through after clicking?

only questions i have

are there steps you have to commence on the software application to get it ready to then detect which redirect request caused when we click around on the site?

and second question

do you have to play around of the stored request traffics it detected to figure out which request is causing the redirect?

**Comment by thisisu** [comment]
I usually just block what appears abnormal. Some of the links are obvious, e.g. if they end in .xyz you can be pretty confident that it's not legitimate. Then I'll apply the test hosts file on my machine to see if the redirect goes away. I can also see false positives here bc if I block something that shouldn't be blocked, parts of the web page won't load. It just takes some trial and error

**Comment by thisisu** [comment]
> > I usually just block what appears abnormal. Some of the links are obvious, e.g. if they end in .xyz you can be pretty confident that it's not legitimate. Then I'll apply the test hosts file on my machine to see if the redirect goes away. I can also see false positives here bc if I block something that shouldn't be blocked, parts of the web page won't load. It just takes some trial and error
> 
> okay but is there something you have to do for the software to detect the redirects or the minute you start the application and go back to the site and test around it starts detecting?
> 
> like im trying to figure out is their some configuration of the software that needs to be done before starting?
> 
> is there measures to take for it begin the process of detecting?
> 
> like what needs to be done on fiddler classic for it to start detecting redirect request
> 
> if you could inform the step by steps if there are any when you open up fiddler that be great!

The minute you start the application it starts logging web traffic.

Check out the guide on how to use Fiddler if interested. It goes into way more detail than I can do here --> https://docs.telerik.com/fiddler/knowledge-base/uiguide
